"""empty message

Revision ID: 2a3915ddcabd
Revises: ead333876c0a
Create Date: 2019-04-25 16:59:32.114233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3915ddcabd'
down_revision = 'ead333876c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_confirmed',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name='users_confirmed__reviewer__fk'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_confirmed__user__fk'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_confirmed')
    # ### end Alembic commands ###
