"""empty message

Revision ID: 2a861245f9ba
Revises: 3258a607632e
Create Date: 2019-04-26 17:27:42.794781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a861245f9ba'
down_revision = '3258a607632e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims_statuses',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name='claims_statuses__claim__fk'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name='claims_statuses__reviewer__fk'),
    sa.PrimaryKeyConstraint('claim_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claims_statuses')
    # ### end Alembic commands ###
