"""empty message

Revision ID: 7c7f60f4c28d
Revises: 1135a2b80727
Create Date: 2019-04-26 15:31:30.241813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7f60f4c28d'
down_revision = '1135a2b80727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theses_comments',
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['theses.id'], name='theses_comments__comment__fk'),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], name='theses_comments__thesis__fk'),
    sa.PrimaryKeyConstraint('thesis_id', 'comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theses_comments')
    # ### end Alembic commands ###
