"""empty message

Revision ID: 825c54ec76e9
Revises: 47559d54efdb
Create Date: 2019-04-27 11:17:10.511636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825c54ec76e9'
down_revision = '47559d54efdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('educations', 'scan_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('educations', 'scan_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
