"""empty message

Revision ID: a2a2627e54de
Revises: 2a3915ddcabd
Create Date: 2019-04-26 10:22:51.215346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a2627e54de'
down_revision = '2a3915ddcabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aspects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aspects_general',
    sa.Column('aspect_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspects.id'], name='aspects_general__aspect__fk'),
    sa.PrimaryKeyConstraint('aspect_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aspects_general')
    op.drop_table('aspects')
    # ### end Alembic commands ###
