"""empty message

Revision ID: f27df6e867ec
Revises: ccae79e2853d
Create Date: 2019-04-26 13:52:35.590085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27df6e867ec'
down_revision = 'ccae79e2853d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('arguments_theses__argument__fk', 'arguments_theses', type_='foreignkey')
    op.drop_constraint('arguments_theses__thesis__fk', 'arguments_theses', type_='foreignkey')
    op.create_foreign_key('arguments_theses__thesis__fk', 'arguments_theses', 'theses', ['thesis_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('arguments_theses__argument__fk', 'arguments_theses', 'arguments', ['argument_id'], ['thesis_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('arguments_theses__argument__fk', 'arguments_theses', type_='foreignkey')
    op.drop_constraint('arguments_theses__thesis__fk', 'arguments_theses', type_='foreignkey')
    op.create_foreign_key('arguments_theses__thesis__fk', 'arguments_theses', 'theses', ['thesis_id'], ['id'])
    op.create_foreign_key('arguments_theses__argument__fk', 'arguments_theses', 'arguments', ['argument_id'], ['thesis_id'])
    # ### end Alembic commands ###
