"""empty message

Revision ID: f8fda014801c
Revises: 927dfab37942
Create Date: 2019-04-26 15:52:48.754857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fda014801c'
down_revision = '927dfab37942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('arguments_theses__thesis__uc', 'arguments_theses', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('arguments_theses__thesis__uc', 'arguments_theses', ['thesis_id'])
    # ### end Alembic commands ###
