"""empty message

Revision ID: faafdc3ed88b
Revises: a2a2627e54de
Create Date: 2019-04-26 10:31:41.039403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faafdc3ed88b'
down_revision = 'a2a2627e54de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_favorites_aspects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['aspects.id'], name='users_favorites_aspects__favorite__fk'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_favorites_aspects__user__fk'),
    sa.PrimaryKeyConstraint('user_id', 'favorite_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_favorites_aspects')
    # ### end Alembic commands ###
