version: "3.5"

services:
  backendapp:
    container_name: backendapp
    build:
      context: ./etc/docker/python
    privileged: true
    command: bash -c "cd backend && bash run_backend.bash"
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app
    networks:
      - elastic

  frontendapp:
    container_name: frontendapp
    build:
      context: ./etc/docker/nginx
    environment:
      - NODE_ENV=development
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/front/dist:/var/www/html/public

  es:
    container_name: es
    environment:
      - discovery.type=single-node
    build:
      context: ./etc/docker/elasticsearch
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge