version: "3.5"

services:
  backendapp:
    container_name: backendapp
    build:
      context: ./etc/docker/python
    privileged: true
    command: bash -c "cd backend && bash run_backend.bash"
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app
    networks:
      - sft

  nginxapp:
    container_name: nginxapp
    build:
      context: ./etc/docker/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - frontendtapp
    networks:
      - sft

  frontendtapp:
    container_name: frontendtapp
    build:
      context: ./etc/docker/nodejs
    command: bash -c "chmod +x start.sh && ./start.sh"
    environment:
      - HOST=0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./src/front:/app
    networks:
      - sft

  es:
    container_name: es
    environment:
      - discovery.type=single-node
    build:
      context: ./etc/docker/elasticsearch
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - sft

networks:
  sft:
    driver: bridge