"""empty message

Revision ID: 1135a2b80727
Revises: 037d00c04a7f
Create Date: 2019-04-26 14:12:02.391388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1135a2b80727'
down_revision = '037d00c04a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_favorites_discussions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['discussions.id'], name='users_favorites_discussions__favorite__fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_favorites_discussions__user__fk'),
    sa.PrimaryKeyConstraint('user_id', 'favorite_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_favorites_discussions')
    # ### end Alembic commands ###
