"""empty message

Revision ID: 1538d1ba24b6
Revises: 2a861245f9ba
Create Date: 2019-04-26 18:47:15.077170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1538d1ba24b6'
down_revision = '2a861245f9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_likes_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('liked_user_id', sa.Integer(), nullable=False),
    sa.Column('liked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['liked_user_id'], ['users.id'], name='users_likes__liked_user__fk'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_likes__user__fk'),
    sa.PrimaryKeyConstraint('user_id', 'liked_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_likes_users')
    # ### end Alembic commands ###
