"""empty message

Revision ID: 2c85b60f360e
Revises: faafdc3ed88b
Create Date: 2019-04-26 11:39:47.226569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c85b60f360e'
down_revision = 'faafdc3ed88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('aspects_general__aspect__fk', 'aspects_general', type_='foreignkey')
    op.create_foreign_key('aspects_general__aspect__fk', 'aspects_general', 'aspects', ['aspect_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_favorites_aspects__favorite__fk', 'users_favorites_aspects', type_='foreignkey')
    op.create_foreign_key('users_favorites_aspects__favorite__fk', 'users_favorites_aspects', 'aspects', ['favorite_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_favorites_aspects__favorite__fk', 'users_favorites_aspects', type_='foreignkey')
    op.create_foreign_key('users_favorites_aspects__favorite__fk', 'users_favorites_aspects', 'aspects', ['favorite_id'], ['id'])
    op.drop_constraint('aspects_general__aspect__fk', 'aspects_general', type_='foreignkey')
    op.create_foreign_key('aspects_general__aspect__fk', 'aspects_general', 'aspects', ['aspect_id'], ['id'])
    # ### end Alembic commands ###
