"""empty message

Revision ID: 3258a607632e
Revises: f8fda014801c
Create Date: 2019-04-26 16:02:15.155200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3258a607632e'
down_revision = 'f8fda014801c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], name='claims__thesis__fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claims')
    # ### end Alembic commands ###
