"""empty message

Revision ID: 47559d54efdb
Revises: 1538d1ba24b6
Create Date: 2019-04-27 11:16:33.493342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47559d54efdb'
down_revision = '1538d1ba24b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('high_school', sa.String(length=50), nullable=False),
    sa.Column('faculty', sa.String(length=100), nullable=False),
    sa.Column('speciality', sa.String(length=100), nullable=False),
    sa.Column('graduation_date', sa.Date(), nullable=False),
    sa.Column('scan_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='educations__user__fk'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('educations_verified',
    sa.Column('education_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['education_id'], ['educations.user_id'], name='educations_verified__education__fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name='educations_verified__reviewer__fk'),
    sa.PrimaryKeyConstraint('education_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('educations_verified')
    op.drop_table('educations')
    # ### end Alembic commands ###
