"""empty message

Revision ID: 69a96f06629b
Revises: 
Create Date: 2019-04-25 11:08:48.159884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a96f06629b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=256), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('fullname', sa.String(length=64), nullable=False),
    sa.Column('avatar_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_deleted',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_deleted__user__fk'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_deleted')
    op.drop_table('users')
    # ### end Alembic commands ###
