"""empty message

Revision ID: 927dfab37942
Revises: 7c7f60f4c28d
Create Date: 2019-04-26 15:42:54.028714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927dfab37942'
down_revision = '7c7f60f4c28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('theses_comments__comment__fk', 'theses_comments', type_='foreignkey')
    op.drop_constraint('theses_comments__thesis__fk', 'theses_comments', type_='foreignkey')
    op.create_foreign_key('theses_comments__thesis__fk', 'theses_comments', 'theses', ['thesis_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('theses_comments__comment__fk', 'theses_comments', 'theses', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('theses_comments__comment__fk', 'theses_comments', type_='foreignkey')
    op.drop_constraint('theses_comments__thesis__fk', 'theses_comments', type_='foreignkey')
    op.create_foreign_key('theses_comments__thesis__fk', 'theses_comments', 'theses', ['thesis_id'], ['id'])
    op.create_foreign_key('theses_comments__comment__fk', 'theses_comments', 'theses', ['comment_id'], ['id'])
    # ### end Alembic commands ###
