"""empty message

Revision ID: bc6248d778d1
Revises: 69a96f06629b
Create Date: 2019-04-25 13:40:52.739720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6248d778d1'
down_revision = '69a96f06629b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users__email__uc', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users__email__uc', 'users', type_='unique')
    # ### end Alembic commands ###
