"""empty message

Revision ID: ccae79e2853d
Revises: 5fa855a3fd73
Create Date: 2019-04-26 13:40:41.381708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccae79e2853d'
down_revision = '5fa855a3fd73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arguments_theses',
    sa.Column('argument_id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['argument_id'], ['arguments.thesis_id'], name='arguments_theses__argument__fk'),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], name='arguments_theses__thesis__fk'),
    sa.PrimaryKeyConstraint('argument_id', 'thesis_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arguments_theses')
    # ### end Alembic commands ###
