"""empty message

Revision ID: ceb2d761f97d
Revises: 2c85b60f360e
Create Date: 2019-04-26 12:08:33.542207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb2d761f97d'
down_revision = '2c85b60f360e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=3), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='discussions__author___fk'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussions_frozen',
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], name='discussions_frozen__discussion__fk'),
    sa.PrimaryKeyConstraint('discussion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussions_frozen')
    op.drop_table('discussions')
    # ### end Alembic commands ###
