"""empty message

Revision ID: ead333876c0a
Revises: f86c0ab04a0a
Create Date: 2019-04-25 15:49:37.469849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead333876c0a'
down_revision = 'f86c0ab04a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_permissions',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_permissions__user__fk'),
    sa.PrimaryKeyConstraint('name', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_permissions')
    # ### end Alembic commands ###
