"""empty message

Revision ID: f1e2db73bf47
Revises: bc6248d778d1
Create Date: 2019-04-25 14:40:52.909652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e2db73bf47'
down_revision = 'bc6248d778d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_favorites_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['users.id'], name='users_favorites_users__favorite__fk'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_favorites_users__user__fk'),
    sa.PrimaryKeyConstraint('user_id', 'favorite_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_favorites_users')
    # ### end Alembic commands ###
