"""empty message

Revision ID: f5c5c90d5aa8
Revises: 4e9ad19c3e2e
Create Date: 2019-04-28 13:28:58.468252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c5c90d5aa8'
down_revision = '4e9ad19c3e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theses_votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('value_x', sa.SmallInteger(), nullable=False),
    sa.Column('value_y', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('flood_divider', sa.Integer(), nullable=False),
    sa.CheckConstraint('flood_divider > 0', name='theses_votes__flood_divider__check'),
    sa.CheckConstraint('value_x >= 0 AND value_x <= 10', name='theses_votes__value_x__check'),
    sa.CheckConstraint('value_y >= 0 AND value_y <= 10', name='theses_votes__value_y__check'),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], name='theses_votes__thesis__fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='theses_votes__user__fk'),
    sa.PrimaryKeyConstraint('user_id', 'thesis_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theses_votes')
    # ### end Alembic commands ###
