"""empty message

Revision ID: f86c0ab04a0a
Revises: f1e2db73bf47
Create Date: 2019-04-25 14:42:48.015008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86c0ab04a0a'
down_revision = 'f1e2db73bf47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_favorites_users', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_favorites_users', 'created_at')
    # ### end Alembic commands ###
